---

title: "Pendrell Vale"
subtitle: "Welcome to"
logo: "assets/icons/tabernacle.png"

header: true
footer: false

theme: default

stylesheet:
  - 'assets/background.css'

links:
  - name: "music players"
    icon: "fas fa-headphones"
    url: "#music-players"

defaults:
  layout: list

services:
  - name: "Gallery"
    icon: "fas fa-fire"
    items:
      - name: "Planar Bridge"
        icon: "fa-solid fa-bullseye"
        url: "https://mendess.xyz"
        target: "_blank"
      - name: "Filmes e Series"
        subtitle: "jellyfin"
        icon: "fa-solid fa-film"
        url: "https://jellyfin.mendess.xyz"
        target: "_blank"
      - name: "Fotos"
        subtitle: "immich"
        icon: "fa-solid fa-images"
        url: "https://immich.mendess.xyz"
        target: "_blank"
      - name: "Musica"
        subtitle: "navidrome - experimenta os music players acima"
        icon: "fa-solid fa-music"
        url: "https://navidrome.mendess.xyz"
        target: "_blank"
      - name: "Podcasts"
        subtitle: "audiobookshelf"
        icon: "fa-solid fa-podcast"
        url: "https://audiobookshelf.mendess.xyz"
        target: "_blank"

  - name: "Tools"
    icon: "fas fa-wrench"
    items:
      - name: "Grafana"
        icon: "fa-solid fa-chart-line"
        url: "https://grafana.mendess.xyz"
        target: "_blank"
      - name: "Home Assistant"
        icon: "fa-solid fa-bell-concierge"
        url: "https://homeassistant.mendess.xyz"
        target: "_blank"
      - name: "Nextcloud"
        type: "Nextcloud"
        icon: "fa-solid fa-cloud"
        url: "https://nextcloud.mendess.xyz"
        target: "_blank"
      - name: "Receitas"
        subtitle: "tandoor"
        icon: "fa-solid fa-kitchen-set"
        url: "https://recipes.mendess.xyz"
      - name: "Password Manager"
        subtitle: "VaultWarden"
        type: "Vaultwarden"
        icon: "fa-solid fa-shield-halved"
        url: "https://pass.mendess.xyz"

  - name: "Alto Mar"
    icon: "fas fa-ship"
    items:
      - name: "Prowlarr"
        subtitle: "Pirate Captain"
        icon: "fa-solid fa-skull-crossbones"
        url: "https://prowlarr.mendess.xyz"
        target: "_blank"
      - name: "Radarr"
        subtitle: "movies"
        icon: "fa-solid fa-film"
        url: "https://radarr.mendess.xyz"
        target: "_blank"
      - name: "Sonarr"
        subtitle: "series"
        icon: "fa-solid fa-tv"
        url: "https://sonarr.mendess.xyz"
        target: "_blank"
      - name: "Lidarr"
        subtitle: "music"
        icon: "fa-solid fa-music"
        url: "https://lidarr.mendess.xyz"
        target: "_blank"
      - name: "Bazarr"
        subtitle: "subtitles"
        icon: "fa-solid fa-font"
        url: "https://bazarr.mendess.xyz"
        target: "_blank"
      - name: "qBittorrent"
        icon: "fa-solid fa-download"
        url: "https://qbittorrent.mendess.xyz"
        target: "_blank"
