services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: ${PUID}:${PGID}
    ports:
      - 8096:8096
      - 7359:7359
    volumes:
      - ${CONFIG_DIR}/gallery/jellyfin/config:/config
      - ${DB_DIR}/gallery/jellyfin/cache:/cache
      - type: bind
        source: ${DATA_DIR}/alto-mar/media
        target: /media
    restart: unless-stopped
    # Optional - alternative address used for autodiscovery
    # environment:
    #   - JELLYFIN_PublishedServerUrl=http://example.com
