# Configuration file for dnsmasq.
#
# Format is one option per line, legal options are the same
# as the long options legal on the command line. See
# "/usr/sbin/dnsmasq --help" or "man 8 dnsmasq" for details.

port=5553 # move dns to 5553

# DHCP
interface=enp4s0
#bind-interfaces
dhcp-range=192.168.42.100,192.168.42.254,255.255.255.0,24h
dhcp-option=option:router,192.168.42.1
dhcp-option=option:dns-server,192.168.42.2
dhcp-option=option6:dns-server,[::]
expand-hosts
domain=lan
local=/lan/
enable-ra

log-queries
log-dhcp
log-debug
