- id: '1771246066484'
  alias: Welcome home
  description: ''
  triggers:
  - trigger: zone.occupancy_detected
    options:
      for: 00:00:00
      zone: zone.home
  conditions:
  - condition: not
    conditions:
    - condition: state
      entity_id: binary_sensor.ornithopter_connected_to_xm5
      state:
      - 'on'
  - condition: time
    after: 08:00:00
    before: '23:40:00'
  actions:
  - action: script.boot_to_source
    metadata: {}
    data:
      source: PC
      volume: 0.1
  mode: single
- id: '1771331270206'
  alias: Leave home
  description: ''
  triggers:
  - trigger: zone.occupancy_cleared
    options:
      for: 00:00:00
      zone: zone.home
  - trigger: event
    event_type: mobile_app_notification_action
    event_data:
      action: notification::tolaria-is-on
    id: turn-off-tolaria
  conditions: []
  actions:
  - if:
    - condition: trigger
      id:
      - turn-off-tolaria
    then:
    - action: switch.turn_off
      metadata: {}
      target:
        entity_id: switch.tolaria
      data: {}
    else:
    - action: switch.turn_off
      metadata: {}
      data: {}
      target:
        entity_id: switch.aramathinewall_power_button
    - if:
      - condition: state
        entity_id: switch.tolaria
        state:
        - 'on'
      then:
      - action: notify.mobile_app_ornithopter
        metadata: {}
        data:
          title: tolaria on
          message: deixaste o fixo ligado
          data:
            actions:
            - action: notification::tolaria-is-on
              title: Turn off tolaria
  mode: single
- id: '1771934637797'
  alias: Avisar a Andreia <3
  description: ''
  triggers:
  - type: battery_level
    device_id: 2d2c2820b54f2d03eecd136594a62365
    entity_id: f982c0eb5ef422cd77b9e8a6faa6f966
    domain: sensor
    trigger: device
    below: 20
  conditions:
  - condition: device
    device_id: 2d2c2820b54f2d03eecd136594a62365
    domain: device_tracker
    entity_id: dd8d91c3d376dfb09b50e31442f4825e
    type: is_not_home
  actions:
  - action: notify.mobile_app_pixel_9a
    metadata: {}
    data:
      title: Tens pouca bateria no telemovel!
      message: "Se calhar era melhor por a carregar \U0001F917"
  mode: single
- id: '1772244305879'
  alias: Start Gaming Mode
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - input_boolean.gaming_mode
    id: 'on'
    to:
    - 'on'
  - trigger: state
    entity_id:
    - input_boolean.gaming_mode
    to:
    - 'off'
    id: 'off'
  conditions: []
  actions:
  - if:
    - condition: trigger
      id:
      - 'on'
    then:
    - action: script.turn_on_tolaria_w_steam_if_tolaria_is_off
      metadata: {}
      data: {}
      enabled: true
    - action: switch.turn_on
      metadata: {}
      target:
        entity_id: switch.aramathinewall_power_button
      data: {}
    - action: switch.turn_on
      metadata: {}
      target:
        entity_id:
        - switch.tv_screen_switch
      data: {}
    - action: notify.lg_webos_tv_oled65b46la_deuqljp
      metadata: {}
      data:
        message: waiting for tolaria to boot up
      continue_on_error: true
    - action: shell_command.wait_for_tolaria
      metadata: {}
      data: {}
    - action: notify.lg_webos_tv_oled65b46la_deuqljp
      metadata: {}
      data:
        message: waiting for steam to boot up
      continue_on_error: true
    - action: shell_command.tolaria_wait_for_steam
      metadata: {}
      data: {}
    - action: script.boot_to_source
      metadata: {}
      data:
        source: PC
    - alias: wait for tolaria to come online
      wait_template: '{{ is_state("switch.tolaria", "on") }}'
      continue_on_timeout: true
      timeout:
        hours: 0
        minutes: 1
        seconds: 0
        milliseconds: 0
    - if:
      - condition: switch.is_off
        target:
          entity_id: switch.tolaria
        options:
          behavior: any
          for: 00:00:00
      then:
      - action: notify.lg_webos_tv_oled65b46la_deuqljp
        metadata: {}
        data:
          message: tolaria is still offline
        continue_on_error: true
      - stop: tolaria is still offline
        error: true
      alias: check if tolaria booted up
    - alias: start steam link
      action: shell_command.host_run
      metadata: {}
      data:
        command: /usr/bin/shyprctl l flatpak run com.valvesoftware.SteamLink --autoconnect
    - alias: fade out music
      parallel:
      - alias: reduce tv volume to 25
        repeat:
          while:
          - condition: numeric_state
            entity_id: media_player.aramanthinewall
            attribute: volume_level
            above: 0.25
          sequence:
          - action: media_player.volume_down
            metadata: {}
            target:
              entity_id: media_player.aramanthinewall
            data: {}
          - delay:
              hours: 0
              minutes: 0
              seconds: 0.5
              milliseconds: 0
      - action: shell_command.host_run
        metadata: {}
        data:
          command: /usr/local/bin/fade-out-music
        alias: Fade out music
    - action: script.adjust_tv_volume
      metadata: {}
      data:
        volume: 0.25
    else:
    - action: shell_command.host_run
      metadata: {}
      data:
        command: /usr/bin/pkill fade-out-music
    - action: media_player.volume_set
      metadata: {}
      target:
        entity_id: media_player.aramanthinewall
      data:
        volume_level: 0.1
    - parallel:
      - action: shell_command.host_run
        metadata: {}
        data:
          command: /usr/local/bin/fade-in-music
        alias: Fade in music
      - action: shell_command.tolaria_restore_resolution
        metadata: {}
        data: {}
      alias: fade in music and restore tolaria resolution
  mode: restart
- id: '1773967837355'
  alias: Screen turns on when tv turns on
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - switch.aramathinewall_power_button
    to:
    - 'on'
    id: 'on'
  - trigger: state
    entity_id:
    - switch.aramathinewall_power_button
    to:
    - 'off'
    id: 'off'
  conditions: []
  actions:
  - if:
    - condition: trigger
      id:
      - 'on'
    then:
    - action: input_boolean.turn_on
      metadata: {}
      target:
        entity_id: input_boolean.tv_screen
      data: {}
    else:
    - action: input_boolean.turn_off
      metadata: {}
      target:
        entity_id: input_boolean.tv_screen
      data: {}
  mode: restart
- id: '1775574119677'
  alias: Backup Alert Notification
  description: ''
  triggers:
  - trigger: webhook
    allowed_methods:
    - POST
    - PUT
    local_only: true
    webhook_id: backup-notification
  conditions: []
  actions:
  - action: persistent_notification.create
    metadata: {}
    data:
      title: Backup Alert for {{ trigger.json.repository }}
      message: '{{ trigger.json.message }}'
  - action: notify.mobile_app_ornithopter
    metadata: {}
    data:
      message: '{{ trigger.json.message }}'
      title: Backup Alert for {{ trigger.json.repository }}
  mode: single
- id: '1775574197183'
  alias: latest-backup-update
  description: ''
  triggers:
  - trigger: webhook
    allowed_methods:
    - POST
    - PUT
    local_only: true
    webhook_id: latest-backup-update
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ "local" in trigger.json.repository }}'
      sequence:
      - action: input_datetime.set_datetime
        metadata: {}
        target:
          entity_id: input_datetime.latest_backup_local
        data:
          datetime: '{{ now() }}'
    - conditions:
      - condition: template
        value_template: '{{ "flopy" in trigger.json.repository }}'
      sequence:
      - action: input_datetime.set_datetime
        metadata: {}
        data:
          datetime: '{{ now() }}'
        target:
          entity_id: input_datetime.latest_backup_flopy
  mode: single
- id: '1776289999583'
  alias: turn off tv when sleeping
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - event.sleep_as_android_sleep_tracking
    attribute: event_type
    to:
    - started
    - resumed
  - trigger: switch.turned_on
    target:
      entity_id: input_boolean.sleeping
    options:
      behavior: each
      for: 00:00:00
  conditions:
  - condition: switch.is_off
    target:
      entity_id: input_boolean.gaming_mode
    options:
      behavior: any
      for: 00:00:00
  actions:
  - action: switch.turn_off
    metadata: {}
    target:
      entity_id: switch.aramathinewall_power_button
    data: {}
  mode: single
- id: '1776790105614'
  alias: Ver as noticias quando acordo
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - event.sleep_as_android_alarm_clock
    attribute: event_type
    to:
    - alert_dismiss
    for:
      hours: 0
      minutes: 10
      seconds: 0
  conditions:
  - condition: time
    before: 09:30:00
  - condition: state
    entity_id: person.mendess
    state:
    - home
  - condition: state
    entity_id: event.sleep_as_android_sleep_tracking
    state:
    - stopped
    attribute: event_type
  actions:
  - if:
    - condition: zone
      entity_id: person.andreia
      zone: zone.home
    then:
    - action: script.boot_to_source
      metadata: {}
      data:
        source: Live TV
        volume: 0
      alias: Boot to Live TV, volume = 0
    else:
    - action: script.boot_to_source
      metadata: {}
      data:
        source: Live TV
        volume: 0.16
      alias: Boot to Live TV, volume = 16
  - action: webostv.button
    metadata: {}
    data:
      entity_id: media_player.aramanthinewall
      button: '6'
    alias: Mudar para RTP Noticias
  mode: single
- id: '1777300497238'
  alias: Backup stale alert
  description: ''
  triggers:
  - trigger: time
    at:
      entity_id: input_datetime.latest_backup_flopy
      offset: '168:00:00'
  - trigger: time
    at:
      entity_id: input_datetime.latest_backup_local
      offset: '168:00:00'
  conditions: []
  actions:
  - action: persistent_notification.create
    metadata: {}
    data:
      message: There is a backup that has gone very stale
      title: Backup stale alert
  - action: notify.mobile_app_ornithopter
    metadata: {}
    data:
      message: There is a backup that has gone very stale
      title: Backup stale alert
  mode: single
- id: '1779702947947'
  alias: Turn off tv screen while working
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.oboro
    from:
    to:
    - 'on'
    for:
      hours: 0
      minutes: 30
      seconds: 0
  - trigger: state
    entity_id:
    - media_player.aramanthinewall
    for:
      hours: 0
      minutes: 30
      seconds: 0
    attribute: source
    to:
    - PC
    - Live TV
  - trigger: state
    entity_id:
    - switch.tv_screen_switch
    to:
    - 'on'
    for:
      hours: 0
      minutes: 30
      seconds: 0
  conditions:
  - condition: time
    after: 09:00:00
    before: '18:00:00'
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  - condition: state
    entity_id: media_player.aramanthinewall
    state:
    - PC
    - Live TV
    attribute: source
    for:
      hours: 0
      minutes: 29
      seconds: 0
  - condition: state
    entity_id: switch.tv_screen_switch
    state:
    - 'on'
    for:
      hours: 0
      minutes: 29
      seconds: 0
  - condition: state
    entity_id: binary_sensor.oboro
    state:
    - 'on'
    for:
      hours: 0
      minutes: 29
      seconds: 0
  actions:
  - action: notify.lg_webos_tv_oled65b46la_deuqljp
    metadata: {}
    data:
      message: Turning off tv screen because you're working
      title: Turn of tv scree while working
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - action: switch.turn_off
    metadata: {}
    target:
      entity_id: switch.tv_screen_switch
    data: {}
  - if:
    - condition: state
      entity_id: binary_sensor.aramanthinewall_source_is_live_tv
      state:
      - 'on'
    then:
    - action: switch.turn_off
      metadata: {}
      target:
        entity_id: switch.aramathinewall_power_button
      data: {}
    alias: turn off tv if watching the news
  mode: single
- id: '1781087126490'
  alias: Pilula alert
  description: ''
  triggers:
  - trigger: time
    at: '22:00:00'
    id: antibabypillen
  - trigger: time
    at: 08:00:00
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    id: heart
  - trigger: time
    at: 09:00:00
    id: heart
    weekday:
    - sun
    - sat
  - trigger: counter.maximum_reached
    target:
      entity_id: counter.antibabypillen_counter
    options:
      behavior: each
      for: 00:00:00
    id: counter reset
  conditions: []
  actions:
  - if:
    - condition: trigger
      id:
      - counter reset
    then:
    - action: counter.reset
      metadata: {}
      target:
        entity_id: counter.antibabypillen_counter
      data: {}
    - stop: done
    alias: Reset counter
  - alias: Increment Antibabypillen counter
    if:
    - condition: trigger
      id:
      - antibabypillen
    then:
    - action: counter.increment
      metadata: {}
      target:
        entity_id: counter.antibabypillen_counter
      data: {}
    - alias: Stop if doing pill interval
      condition: counter.is_value
      options:
        threshold:
          type: below
          value:
            active_choice: number
            number: 22
      target:
        entity_id: counter.antibabypillen_counter
  - variables:
      message: '{%- if trigger.id == "heart" %} Protect your heart {%- elif trigger.id
        == "antibabypillen" %} Antibabypillen {{ states("counter.antibabypillen_counter")}}:
        Vai tomar isso {%- else %} You need to take some meds, but I don''t know which
        {%- endif %}'
  - action: input_boolean.turn_on
    metadata: {}
    target:
      entity_id: input_boolean.antibabipillen
    data: {}
  - wait_for_trigger:
    - trigger: switch.turned_off
      target:
        entity_id: input_boolean.antibabipillen
      options:
        behavior: each
        for: 00:00:00
    timeout:
      hours: 1
      minutes: 0
      seconds: 0
      milliseconds: 0
  - repeat:
      while:
      - condition: state
        entity_id: input_boolean.antibabipillen
        state:
        - 'on'
      sequence:
      - if:
        - condition: state
          entity_id: switch.aramathinewall_power_button
          state:
          - 'on'
        - condition: zone.in_zone
          target:
            entity_id: person.andreia
          options:
            for: 00:00:00
            zone: zone.home
          enabled: true
        then:
        - action: notify.lg_webos_tv_oled65b46la_deuqljp
          metadata: {}
          data:
            message: '{{ message }}'
        - delay:
            hours: 0
            minutes: 0
            seconds: 7
            milliseconds: 0
        else:
        - action: notify.mobile_app_pixel_9a
          metadata: {}
          data:
            message: '{{ message }}'
        - delay:
            hours: 0
            minutes: 30
            seconds: 0
            milliseconds: 0
  mode: single
- id: '1783362865967'
  alias: Update estores
  description: ''
  triggers:
  - trigger: state
    entity_id: input_boolean.sleeping
  - trigger: state
    entity_id: input_boolean.gaming_mode
  - trigger: state
    entity_id: binary_sensor.daylight
  - trigger: state
    entity_id: sensor.sun_solar_azimuth
  - trigger: state
    entity_id: binary_sensor.aramanthinewall_source_is_jellyfin
  - trigger: state
    entity_id: input_boolean.privacy
  - trigger: timer.finished
    target:
      entity_id: timer.cover_grace_period
    options:
      behavior: each
      for: 00:00:00
  conditions:
  - condition: timer.is_idle
    target:
      entity_id: timer.cover_grace_period
    options:
      for: 00:00:00
  actions:
  - variables:
      azimuth: '{{ int(states(''sensor.sun_solar_azimuth'')) }}'
      lower_target: '{%- set max_temp = states("sensor.max_temp") %} {%- set temp
        = 0 if max_temp == "unknown" else float(max_temp) %} {{ 100 if temp < 28 else
        30 }}'
      lower_east: '{{ lower_target if azimuth < 130 else 100 }}'
      lower_south: '{{ lower_target if 100 < azimuth < 200 else 100 }}'
      lower_west: '{{ lower_target if 150 < azimuth else 100 }}'
      daytime_target: '{{ 0 if states(''binary_sensor.daylight'') == ''off'' else
        100 }}'
      media_target: '{{ 0 if states(''input_boolean.gaming_mode'') == ''true'' or
        states(''binary_sensor.aramanthinewall_source_is_jellyfin'') == ''true'' else
        100 }}'
      sleeping_target: '{{ 0 if states(''input_boolean.sleeping'') == ''on'' else
        100 }}'
      privacy: '{{ lower_target if states(''input_boolean.privacy'') == ''on'' else
        100 }}'
      _: calculations
      calculations:
      - entity: cover.estores_varanda
        motors:
        - sensor.estores_varanda_direira_motor_run_status
        - sensor.estores_varanda_esquerda_motor_run_status
        position: '{{ min(daytime_target, lower_east, media_target, sleeping_target,
          privacy) }}'
      - entity: cover.estores_tv
        motors:
        - sensor.estores_tv_motor_run_status
        position: '{{ min(daytime_target, lower_south, media_target, sleeping_target,
          privacy) }}'
      - entity: cover.estores_wc
        motors:
        - sensor.estores_wc_motor_run_status
        position: '{{ min(daytime_target, lower_south, sleeping_target) }}'
      - entity: cover.estores_quarto
        motors:
        - sensor.estores_quarto_motor_run_status
        position: '{{ min(daytime_target, lower_west, sleeping_target) }}'
  - repeat:
      for_each: '{{ calculations }}'
      sequence:
      - action: script.set_cover_position_with_grace_interval
        metadata: {}
        data:
          position: '{{ repeat.item.position }}'
          cover: '{{ repeat.item.entity }}'
          motor: '{{ repeat.item.motors }}'
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - action: timer.cancel
    metadata: {}
    target:
      entity_id: timer.cover_grace_period
    data: {}
  mode: queued
  max: 10
- id: '1783363775126'
  alias: Toggle sleeping
  description: ''
  triggers:
  - trigger: time
    at: 03:00:00
    id: 'on'
  - trigger: time
    at: '10:00:00'
    id: 'on'
  conditions: []
  actions:
  - if:
    - condition: trigger
      id:
      - 'on'
    then:
    - action: input_boolean.turn_on
      metadata: {}
      target:
        entity_id: input_boolean.sleeping
      data: {}
    else:
    - action: input_boolean.turn_off
      metadata: {}
      target:
        entity_id: input_boolean.sleeping
      data: {}
  mode: single
- id: '1783368297736'
  alias: Start estores grace period
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - cover.estores_todos
    attribute: current_position
  conditions: []
  actions:
  - action: timer.start
    metadata: {}
    target:
      entity_id: timer.cover_grace_period
    data: {}
  mode: single
