- id: '1771246066484'
  alias: Welcome home
  description: ''
  triggers:
  - device_id: 63e3d64a1a19eff86f97a51317750168
    domain: device_tracker
    entity_id: 436c9eb2cc16d3c98b8af6324030d4ce
    type: enters
    trigger: device
    zone: zone.home
  conditions:
  - condition: not
    conditions:
    - condition: state
      entity_id: binary_sensor.ornithopter_connected_to_xm5
      state:
      - 'on'
  - condition: time
    after: 08:00:00
    before: '23:40:00'
  actions:
  - action: script.boot_to_source
    metadata: {}
    data:
      source: PC
  mode: single
- id: '1771331270206'
  alias: Leave home
  description: ''
  triggers:
  - device_id: 63e3d64a1a19eff86f97a51317750168
    domain: device_tracker
    entity_id: 436c9eb2cc16d3c98b8af6324030d4ce
    type: leaves
    trigger: device
    zone: zone.home
  conditions: []
  actions:
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.aramathinewall_power_button
  mode: single
- id: '1771934637797'
  alias: Avisar a Andreia <3
  description: ''
  triggers:
  - type: battery_level
    device_id: 2d2c2820b54f2d03eecd136594a62365
    entity_id: f982c0eb5ef422cd77b9e8a6faa6f966
    domain: sensor
    trigger: device
    below: 20
  conditions:
  - condition: device
    device_id: 2d2c2820b54f2d03eecd136594a62365
    domain: device_tracker
    entity_id: dd8d91c3d376dfb09b50e31442f4825e
    type: is_not_home
  actions:
  - action: notify.mobile_app_pixel_9a
    metadata: {}
    data:
      title: Tens pouca bateria no telemovel!
      message: "Se calhar era melhor por a carregar \U0001F917"
  mode: single
- id: '1772244305879'
  alias: Start Gaming Mode
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - input_boolean.gaming_mode
    to:
    - 'on'
  conditions: []
  actions:
  - action: script.turn_on_tolaria_w_steam_if_tolaria_is_off
    metadata: {}
    data: {}
    enabled: true
  - action: switch.turn_on
    metadata: {}
    target:
      entity_id:
      - switch.tv_screen_switch
    data: {}
  - action: script.boot_to_source
    metadata: {}
    data:
      source: PC
  - action: shell_command.host_run
    metadata: {}
    data:
      command: /usr/bin/shyprctl l flatpak run com.valvesoftware.SteamLink
    alias: start steam link
  - wait_template: '{{ states("switch.tolaria", "on") }}'
    continue_on_timeout: true
    alias: wait for tolaria to come online
  - action: shell_command.host_run
    metadata: {}
    data:
      command: /usr/local/bin/fade-out-music
    alias: Fade out music
  - repeat:
      while:
      - condition: numeric_state
        entity_id: media_player.aramanthinewall
        attribute: volume_level
        below: 0.25
      sequence:
      - action: media_player.volume_up
        metadata: {}
        target:
          entity_id: media_player.aramanthinewall
        data: {}
      - delay:
          hours: 0
          minutes: 0
          seconds: 1
          milliseconds: 0
  mode: single
- id: '1773967837355'
  alias: Screen turns on when tv turns on
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - switch.aramathinewall_power_button
    to:
    - 'on'
  conditions: []
  actions:
  - action: input_boolean.turn_on
    metadata: {}
    target:
      entity_id: input_boolean.tv_screen
    data: {}
  mode: single
- id: '1775378866438'
  alias: Morning open covers
  description: ''
  triggers:
  - trigger: time
    at: 08:00:00
  conditions: []
  actions:
  - action: cover.open_cover
    metadata: {}
    data: {}
    target:
      label_id: estores_sala
  - if:
    - condition: not
      conditions:
      - condition: zone
        entity_id: person.mendess
        zone: zone.home
    then:
    - action: cover.open_cover
      metadata: {}
      target:
        label_id: estores_quarto
      data: {}
  mode: single
- id: '1775379350361'
  alias: Close shutters when tv turns on
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - input_boolean.gaming_mode
    to:
    - 'on'
  - trigger: state
    entity_id:
    - media_player.aramanthinewall
    attribute: source
    for:
      hours: 0
      minutes: 0
      seconds: 10
    to:
    - Jellyfin
  conditions: []
  actions:
  - action: cover.close_cover
    metadata: {}
    data: {}
    target:
      label_id: estores_sala
  mode: single
- id: '1775381062641'
  alias: Close estores when night falls
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.night_time
    to:
    - 'off'
  conditions: []
  actions:
  - action: cover.close_cover
    metadata: {}
    data: {}
    target:
      label_id: estores_all
  mode: single
- id: '1775383359573'
  alias: Stopped watching tv
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - input_boolean.gaming_mode
    to:
    - 'off'
  - trigger: state
    entity_id:
    - media_player.aramanthinewall
    attribute: source
    to:
    - PC
    for:
      hours: 0
      minutes: 1
      seconds: 0
  conditions:
  - condition: state
    entity_id: binary_sensor.night_time
    state:
    - 'on'
  - condition: state
    entity_id: switch.aramathinewall_power_button
    state:
    - 'on'
  - condition: state
    entity_id: input_boolean.gaming_mode
    state:
    - 'off'
  actions:
  - action: cover.open_cover
    metadata: {}
    target:
      label_id: estores_sala
    data: {}
  mode: single
- id: '1775386644374'
  alias: Stop Gaming mode
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - input_boolean.gaming_mode
    to:
    - 'off'
  conditions: []
  actions:
  - action: media_player.volume_set
    metadata: {}
    target:
      entity_id: media_player.aramanthinewall
    data:
      volume_level: 0.1
  - parallel:
    - action: shell_command.host_run
      metadata: {}
      data:
        command: /usr/local/bin/fade-in-music
      alias: Fade in music
    - action: shell_command.tolaria_restore_resolution
      metadata: {}
      data: {}
  mode: single
- id: '1775574119677'
  alias: Backup Alert Notification
  description: ''
  triggers:
  - trigger: webhook
    allowed_methods:
    - POST
    - PUT
    local_only: true
    webhook_id: backup-notification
  conditions: []
  actions:
  - action: persistent_notification.create
    metadata: {}
    data:
      title: Backup Alert for {{ trigger.json.repository }}
      message: '{{ trigger.json.message }}'
  - action: notify.mobile_app_ornithopter
    metadata: {}
    data:
      message: '{{ trigger.json.message }}'
      title: Backup Alert for {{ trigger.json.repository }}
  mode: single
- id: '1775574197183'
  alias: latest-backup-update
  description: ''
  triggers:
  - trigger: webhook
    allowed_methods:
    - POST
    - PUT
    local_only: true
    webhook_id: latest-backup-update
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ "local" in trigger.json.repository }}'
      sequence:
      - action: input_datetime.set_datetime
        metadata: {}
        target:
          entity_id: input_datetime.latest_backup_local
        data:
          datetime: '{{ now() }}'
    - conditions:
      - condition: template
        value_template: '{{ "flopy" in trigger.json.repository }}'
      sequence:
      - action: input_datetime.set_datetime
        metadata: {}
        data:
          datetime: '{{ now() }}'
        target:
          entity_id: input_datetime.latest_backup_flopy
  mode: single
- id: '1776161237853'
  alias: Smart Wake up
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - event.sleep_as_android_smart_wake_up
    attribute: event_type
    to:
    - before_smart_period
    for:
      hours: 0
      minutes: 30
      seconds: 0
  conditions:
  - condition: zone
    entity_id: person.mendess
    zone: zone.home
  actions:
  - action: cover.set_cover_position
    metadata: {}
    data:
      position: 10
    target:
      entity_id: cover.estores_quarto_wc
  mode: single
- id: '1776261226221'
  alias: Abrir estores quando o alarme toca
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - event.sleep_as_android_alarm_clock
    attribute: event_type
    to:
    - alert_start
  conditions:
  - condition: zone
    entity_id: person.mendess
    zone: zone.home
  actions:
  - repeat:
      while:
      - condition: numeric_state
        entity_id: cover.estores_quarto_wc
        attribute: current_position
        below: 100
      sequence:
      - action: cover.set_cover_position
        metadata: {}
        target:
          entity_id: cover.estores_quarto_wc
        data:
          position: '{{ min(100, (state_attr(''cover.estores_quarto_wc'', ''current_position'')
            + 10)) }}'
      - delay:
          hours: 0
          minutes: 2
          seconds: 0
          milliseconds: 0
  mode: single
- id: '1776289999583'
  alias: turn off tv when sleeping
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - event.sleep_as_android_sleep_tracking
  conditions: []
  actions:
  - action: switch.turn_off
    metadata: {}
    target:
      entity_id: switch.aramathinewall_power_button
    data: {}
  mode: single
- id: '1776790105614'
  alias: Ver as noticias quando acordo
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - event.sleep_as_android_alarm_clock
    attribute: event_type
    to:
    - alert_dismiss
    for:
      hours: 0
      minutes: 10
      seconds: 0
  conditions:
  - condition: time
    before: 09:30:00
  - condition: state
    entity_id: person.mendess
    state:
    - home
  actions:
  - action: script.boot_to_source
    metadata: {}
    data:
      source: Live TV
  - action: media_player.volume_set
    metadata: {}
    target:
      device_id: b5098e373bea279a182da7c91e908c4f
    data:
      volume_level: 0.1
  - action: webostv.button
    metadata: {}
    data:
      entity_id: media_player.aramanthinewall
      button: '6'
  mode: single
