- id: '1771246066484'
  alias: Welcome home
  description: ''
  triggers:
  - device_id: 63e3d64a1a19eff86f97a51317750168
    domain: device_tracker
    entity_id: 436c9eb2cc16d3c98b8af6324030d4ce
    type: enters
    trigger: device
    zone: zone.home
  conditions:
  - condition: not
    conditions:
    - condition: state
      entity_id: binary_sensor.ornithopter_connected_to_xm5
      state:
      - 'on'
  actions:
  - action: script.wake_aramanthinewall
    metadata: {}
    data: {}
  mode: single
- id: '1771331270206'
  alias: Leave home
  description: ''
  triggers:
  - device_id: 63e3d64a1a19eff86f97a51317750168
    domain: device_tracker
    entity_id: 436c9eb2cc16d3c98b8af6324030d4ce
    type: leaves
    trigger: device
    zone: zone.home
  conditions: []
  actions:
  - action: webostv.command
    metadata: {}
    data:
      command: system/turnOff
      entity_id: media_player.aramanthinewall
  mode: single
- id: '1771934637797'
  alias: Avisar a Andreia <3
  description: ''
  triggers:
  - type: battery_level
    device_id: 2d2c2820b54f2d03eecd136594a62365
    entity_id: f982c0eb5ef422cd77b9e8a6faa6f966
    domain: sensor
    trigger: device
    below: 20
  conditions:
  - condition: device
    device_id: 2d2c2820b54f2d03eecd136594a62365
    domain: device_tracker
    entity_id: dd8d91c3d376dfb09b50e31442f4825e
    type: is_not_home
  actions:
  - action: notify.mobile_app_pixel_9a
    metadata: {}
    data:
      title: Tens pouca bateria no telemovel!
      message: "Se calhar era melhor por a carregar \U0001F917"
  mode: single
- id: '1772244305879'
  alias: Start Gaming Mode
  description: ''
  triggers:
  - trigger: webhook
    allowed_methods:
    - POST
    local_only: true
    webhook_id: start_gaming_mode
  conditions: []
  actions:
  - action: script.wake_aramanthinewall
    metadata: {}
    data: {}
  - action: script.turn_on_tolaria_w_steam_if_tolaria_is_off
    metadata: {}
    data: {}
  mode: single
- id: '1773092194701'
  alias: Set TV Volume 25
  description: ''
  triggers:
  - trigger: webhook
    allowed_methods:
    - POST
    - PUT
    local_only: true
    webhook_id: set_tv_volume_25
  conditions: []
  actions:
  - action: media_player.volume_set
    metadata: {}
    target:
      entity_id: media_player.aramanthinewall
    data:
      volume_level: 0.25
  mode: single
- id: '1773092252112'
  alias: Set TV volume 10
  description: ''
  triggers:
  - trigger: webhook
    allowed_methods:
    - POST
    - PUT
    local_only: true
    webhook_id: set_tv_volume_10
  conditions: []
  actions:
  - action: media_player.volume_set
    metadata: {}
    target:
      entity_id: media_player.aramanthinewall
    data:
      volume_level: 0.1
  mode: single
- id: '1773967837355'
  alias: Screen turns on when tv turns on
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - media_player.aramanthinewall
    from:
    - unavailable
    - 'off'
    to:
  conditions: []
  actions:
  - action: input_boolean.turn_on
    metadata: {}
    target:
      entity_id: input_boolean.tv_screen
    data: {}
  mode: single
