
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1


switch:
  - platform: wake_on_lan
    mac: 24:4b:fe:81:b6:ab
    name: tolaria
    host: tolaria.lan
    turn_off:
      action: shell_command.turn_off_tolaria

shell_command:
  turn_off_tolaria: ./ssh-tolaria.sh sudo shutdown now
  tolaria_turn_on_steam: ./ssh-tolaria.sh shyprctl l /home/mendess/.local/bin/setup-remote-steam
  tolaria_restore_resolution: ./ssh-tolaria.sh shyprctl l /home/mendess/.local/bin/toggle-resolution 21:9
  host_run: ./host-run.sh {{ command }}

logger:
  default: warning
