
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1


switch:
  - platform: wake_on_lan
    mac: 24:4b:fe:81:b6:ab
    name: tolaria
    host: tolaria.lan
    turn_off:
      action: shell_command.turn_off_tolaria

shell_command:
  turn_off_tolaria: ./ssh-tolaria.sh sudo shutdown now
  tolaria_turn_on_steam: ./ssh-tolaria.sh shyprctl l /home/mendess/.local/bin/setup-remote-steam
  tolaria_restore_resolution: ./ssh-tolaria.sh shyprctl l /home/mendess/.local/bin/toggle-resolution 21:9
  tolaria_wait_for_steam: ./ssh-tolaria.sh until pgrep steam -q; do sleep 0.5; done
  host_run: ./host-run.sh {{ command }}

logger:
  default: warning

monitor_docker: !include monitor_docker.yaml

template:
  - trigger:
    - trigger: time
      at: "00:00:01"
    - trigger: homeassistant
      event: start
    - trigger: event
      event_type: event_template_reloaded
    action:
      - action: weather.get_forecasts
        data:
          type: daily
        target:
          entity_id: weather.forecast_home
        response_variable: weather_data
    sensor:
      - name: "Max temperature"
        unique_id: max_daily_temp
        state: >-
          {{ weather_data["weather.forecast_home"].forecast[0].temperature }}
        unit_of_measurement: "°C"
      - name: "Min temperature"
        unique_id: min_daily_temp
        state: >-
          {{ weather_data["weather.forecast_home"].forecast[0].templow }}
        unit_of_measurement: "°C"
