[Interface]
# Server address in VPN virtual LAN
Address = 10.0.2.1/24
ListenPort = 51822
PrivateKey = REPLACE__PRIVATE_KEY

PostUp = nft add table inet ex2
PostUp = nft add chain inet ex2 forward { type filter hook forward priority filter - 1 \; policy accept \; }
PostUp = nft add rule inet ex2 forward iifname "ex2" oifname "enp4s0" accept
PostUp = nft add rule inet ex2 forward iifname "enp4s0" oifname "ex2" ct state established,related accept
PostUp = nft add rule inet ex2 forward iifname "ex2" drop
PostUp = nft add chain inet ex2 postrouting { type nat hook postrouting priority srcnat \; policy accept \; }
PostUp = nft add rule inet ex2 postrouting oifname "enp4s0" masquerade
PostUp = nft add rule ip filter DOCKER-USER iifname "ex2" accept
PostUp = nft add rule ip filter DOCKER-USER oifname "ex2" accept

PostDown = nft -a list chain ip filter DOCKER-USER | grep '"ex2"' | awk '/handle/ {print $NF}' | xargs -I{} nft delete rule ip filter DOCKER-USER handle {}
PostDown = nft delete table inet ex2

#== devices ==========================================
[Peer]
# friendly_name = hugo@phone
PublicKey = 1xo7Lrr/bglquPvg+LghMFYURUS4161Z9IMKoVvYIng=
AllowedIPs = 10.0.2.2/32
