[Interface]
# Server address in VPN virtual LAN
Address = 10.0.2.1/24
ListenPort = 51822
PrivateKey = REPLACE__PRIVATE_KEY

# Tell Docker's firewall chain to allow incoming traffic coming from the "ex2" interface
PostUp = nft add rule ip filter DOCKER-USER iifname "ex2" accept
# Tell Docker's firewall chain to allow outgoing traffic destined for the "ex2" interface
PostUp = nft add rule ip filter DOCKER-USER oifname "ex2" accept

PostDown = nft -a list chain ip filter DOCKER-USER | grep '"ex2"' | awk '/handle/ {print $NF}' | xargs -I{} nft delete rule ip filter DOCKER-USER handle {}


#== devices ==========================================
[Peer]
# friendly_name = hugo@phone
PublicKey = 1xo7Lrr/bglquPvg+LghMFYURUS4161Z9IMKoVvYIng=
AllowedIPs = 10.0.2.2/32

[Peer]
# friendly_name = hugo@macbook
PublicKey = 23FpY8Ougz0C+AyidVOj9LOAaiz5IBlGpxFt6QLBFEU=
AllowedIPs = 10.0.2.6/32

[Peer]
# friendly_name = mendess@phone
PublicKey = Ess+WpvbYplLa6dPkYyU/4cTWRGHJuzr90ZMLhCjo2U=
AllowedIPs = 10.0.2.8/32
