[Interface]
# Server address in VPN virtual LAN
Address = 10.0.3.1/24
ListenPort = 51823
PrivateKey = REPLACE__PRIVATE_KEY

# Tell Docker's firewall chain to allow incoming traffic coming from the "fm3" interface
PostUp = nft add rule ip filter DOCKER-USER iifname "fm3" accept
# Tell Docker's firewall chain to allow outgoing traffic destined for the "fm3" interface
PostUp = nft add rule ip filter DOCKER-USER oifname "fm3" accept

PostDown = nft -a list chain ip filter DOCKER-USER | grep '"fm3"' | awk '/handle/ {print $NF}' | xargs -I{} nft delete rule ip filter DOCKER-USER handle {}


#== devices ==========================================
[Peer]
# friendly_name = cata@iphone
PublicKey = 8uvjV1kXOm+ah9fL8Hv9tNEXFfPlYWfwYwzPuGb1b3o=
AllowedIPs = 10.0.3.31/32

[Peer]
# friendly_name = bete@telemovel
PublicKey = jhRjAdYm0eaiCdMulz3kmwCmY0Jc6GdMLfFSoIspf18=
AllowedIPs = 10.0.3.32/32

[Peer]
# friendly_name = rosa@telemovel
PublicKey = D7YEdxGE5wRr1gVUTyhflqsPo36PmGWUx0GL9HBYyiQ=
AllowedIPs = 10.0.3.33/32

[Peer]
# friendly_name = tete@telemovel
PublicKey = 3VTfPwtkOEF0aJOwuTtRIvlBzLZFYe6O2IXgnGGOmyI=
AllowedIPs = 10.0.3.34/32

[Peer]
# friendly_name = margarida@iphone
PublicKey = aL59AG04epjiPluaXXHdQkSixVIf7MucSPnfR1e6I1Y=
AllowedIPs = 10.0.3.35/32
