[Interface]
# Server address in VPN virtual LAN
Address = 10.0.3.1/24
ListenPort = 51823
PrivateKey = REPLACE__PRIVATE_KEY

# Tell Docker's firewall chain to allow incoming traffic coming from the "fm3" interface
PostUp = nft add rule ip filter DOCKER-USER iifname "fm3" accept
# Tell Docker's firewall chain to allow outgoing traffic destined for the "fm3" interface
PostUp = nft add rule ip filter DOCKER-USER oifname "fm3" accept

PostDown = nft -a list chain ip filter DOCKER-USER | grep '"fm3"' | awk '/handle/ {print $NF}' | xargs -I{} nft delete rule ip filter DOCKER-USER handle {}


#== devices ==========================================

[Peer]
# friendly_name = margarida@iphone
PublicKey = aL59AG04epjiPluaXXHdQkSixVIf7MucSPnfR1e6I1Y=
AllowedIPs = 10.0.3.35/32

[Peer]
# friendly_name = tete@android
PublicKey = NHSv1JamgKG24zsbVW8XZ5b/mZO0OPs13e/y63mN8zY=
AllowedIPs = 10.0.3.37/32

[Peer]
# friendly_name = bete@android
PublicKey = d3q9kW6ou3jHc2XMkzHxIArI6AFJZM0nHQ8lFaywLRM=
AllowedIPs = 10.0.3.38/32

[Peer]
# friendly_name = rosa@android
PublicKey = gUy9wBufXYF32y6TvYgoFOe9qe+6B00KBSsQQMuv4HM=
AllowedIPs = 10.0.3.39/32

[Peer]
# friendly_name = cata@iphone
PublicKey = cufTEL/Oxv6fEZeo5sMvQtYR6vjpVl0ivSh5UYjyXBA=
AllowedIPs = 10.0.3.40/32
