[Interface]
# Server address in VPN virtual LAN
Address = 10.0.1.1/24
ListenPort = 51821
PrivateKey = REPLACE__PRIVATE_KEY

PostUp = nft add table inet mc1
PostUp = nft add chain inet mc1 postrouting { type nat hook postrouting priority srcnat \; policy accept \; }
PostUp = nft add rule inet mc1 postrouting oifname "enp4s0" masquerade
PostUp = nft add rule ip filter DOCKER-USER iifname "mc1" accept
PostUp = nft add rule ip filter DOCKER-USER oifname "mc1" accept

PostDown = nft -a list chain ip filter DOCKER-USER | grep '"mc1"' | awk '/handle/ {print $NF}' | xargs -I{} nft delete rule ip filter DOCKER-USER handle {}
PostDown = nft delete table inet mc1

