services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    user: ${PUID}
    ports:
      - 3000:3000
    volumes:
      - ${DB_DIR}/watch/grafana:/var/lib/grafana
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
  cadvisor:
    image: ghcr.io/google/cadvisor:latest
    container_name: cadvisor
    privileged: true
    ports:
      - 1696:8080
    devices:
      - /dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    restart: unless-stopped
