worker_processes  1;

# Load all installed modules
include modules.d/*.conf;

events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;
    server_names_hash_bucket_size 64;
    types_hash_max_size 2048;
    types_hash_bucket_size 128;

    log_format promethus_log '$remote_addr [$time_local] $request_method $host "$request_uri" $status "$http_user_agent"';

    access_log /var/log/nginx/simple.log promethus_log;

    include /etc/nginx/sites-enabled/public/*;
    include /etc/nginx/sites-enabled/private/*;

    server {
        listen 127.0.0.1:8080;
        location /stub_status {
            stub_status;
            allow 127.0.0.1;
            deny all;
        }
    }
}

