server:
    define-tag: "block-youtube"
    #access-control-tag: 10.0.0.22/32 "block-youtube"

    local-zone: youtube.com refuse
    local-zone: www.youtube.com refuse
    local-zone: youtu.be refuse
    local-zone: www.youtu.be refuse

    local-zone-tag: youtube.com "block-youtube"
    local-zone-tag: www.youtube.com "block-youtube"
    local-zone-tag: youtu.be "block-youtube"
    local-zone-tag: www.youtu.be "block-youtube"
