server:
    access-control-view: 192.168.42.50/32 block-lg-phone-home

view:
    name: "block-lg-phone-home"

    view-first: no

    # Block everything by default
    local-zone: "." refuse

    # my stuff
    local-zone: "mendess.xyz" redirect
    local-data: "mendess.xyz. IN A 192.168.42.2"

    # yt
    local-zone: "youtube.com" transparent
    local-zone: "googlevideo.com" transparent
    local-zone: "ytimg.com" transparent
    local-zone: "youtu.be" transparent
    local-zone: "ggpht.com" transparent
    local-zone: "googleapis.com" transparent
    local-zone: "gstatic.com" transparent
    local-zone: "google.com" transparent
    local-zone: "googleusercontent.com" transparent
    local-zone: "sponsorblock.inf.re" transparent

    # webosbrew
    local-zone: "webosbrew.org" transparent
    local-zone: "github.com" transparent
    local-zone: "githubusercontent.com" transparent
