server:
    access-control-view: 192.168.42.50/32 block-lg-phone-home

view:
    name: "block-lg-phone-home"

    view-first: no

    # Block everything by default
    local-zone: "." refuse

    # my stuff
    local-zone: "mendess.xyz" redirect
    local-data: "mendess.xyz. IN A 192.168.42.2"

    # yt
    local-zone: "youtube.com" transparent
    local-zone: "googlevideo.com" transparent
    local-zone: "ytimg.com" transparent
    local-zone: "youtu.be" transparent
    local-zone: "ggpht.com" transparent
    local-zone: "googleapis.com" transparent
    local-zone: "gstatic.com" transparent
    local-zone: "google.com" transparent
    local-zone: "googleusercontent.com" transparent
    local-zone: "sponsorblock.inf.re" transparent

    # webosbrew
    local-zone: "webosbrew.org" transparent
    local-zone: "github.com" transparent
    local-zone: "githubusercontent.com" transparent
    ## kodi
    local-zone: "kodi.tv" transparent
    local-zone: "ftp.halifax.rwth-aachen.de" transparent
    local-zone: "mirrors.dotsrc.org" transparent
    local-zone: "mirrors.accum.se" transparent
    local-zone: "ftp.snt.utwente.nl" transparent
    local-zone: "mirror.hro.nl" transparent
    local-zone: "jellyfin.org" transparent
    local-zone: "mirror.math.princeton.edu" transparent
    local-zone: "mirror.accum.se" transparent
    local-zone: "ftp.hosteurope.de" transparent
    local-zone: "ftp.cc.uoc.gr" transparent
    local-zone: "mirror.karneval.cz" transparent
    local-zone: "mirror.netcologne.de" transparent
    local-zone: "ftp.nluug.nl" transparent
    local-zone: "ftp.fau.de" transparent
    local-zone: "kodi.mirror.liteserver.nl" transparent
