server:
    local-zone: "pendrellvale.home." redirect
    local-data: "pendrellvale.home. IN A 192.168.42.2"

forward-zone:
    name: "lan."
    forward-addr: 127.0.0.1@5553

forward-zone:
    name: "42.168.192.in-addr.arpa"
    forward-addr: 127.0.0.1@5553
