server:
    local-zone: "pendrellvale.home." redirect
    local-data: "pendrellvale.home. IN A 192.168.42.2"
    local-zone: "bazarr.mendess.xyz." redirect
    local-data: "bazarr.mendess.xyz. IN A 192.168.42.2"
    local-zone: "lidarr.mendess.xyz." redirect
    local-data: "lidarr.mendess.xyz. IN A 192.168.42.2"
    local-zone: "prowlarr.mendess.xyz." redirect
    local-data: "prowlarr.mendess.xyz. IN A 192.168.42.2"
    local-zone: "qbittorrent.mendess.xyz." redirect
    local-data: "qbittorrent.mendess.xyz. IN A 192.168.42.2"
    local-zone: "radarr.mendess.xyz." redirect
    local-data: "radarr.mendess.xyz. IN A 192.168.42.2"
    local-zone: "sonarr.mendess.xyz." redirect
    local-data: "sonarr.mendess.xyz. IN A 192.168.42.2"
    local-zone: "audiobookshelf.mendess.xyz." redirect
    local-data: "audiobookshelf.mendess.xyz. IN A 192.168.42.2"
    local-zone: "immich.mendess.xyz." redirect
    local-data: "immich.mendess.xyz. IN A 192.168.42.2"
    local-zone: "jellyfin.mendess.xyz." redirect
    local-data: "jellyfin.mendess.xyz. IN A 192.168.42.2"
    local-zone: "navidrome.mendess.xyz." redirect
    local-data: "navidrome.mendess.xyz. IN A 192.168.42.2"
    local-zone: "homeassistant.mendess.xyz." redirect
    local-data: "homeassistant.mendess.xyz. IN A 192.168.42.2"
    local-zone: "home.mendess.xyz." redirect
    local-data: "home.mendess.xyz. IN A 192.168.42.2"
    local-zone: "nextcloud.mendess.xyz." redirect
    local-data: "nextcloud.mendess.xyz. IN A 192.168.42.2"
    local-zone: "recipes.mendess.xyz." redirect
    local-data: "recipes.mendess.xyz. IN A 192.168.42.2"
    local-zone: "pass.mendess.xyz." redirect
    local-data: "pass.mendess.xyz. IN A 192.168.42.2"
    local-zone: "zigbee2mqtt.mendess.xyz." redirect
    local-data: "zigbee2mqtt.mendess.xyz. IN A 192.168.42.2"
    local-zone: "grafana.mendess.xyz." redirect
    local-data: "grafana.mendess.xyz. IN A 192.168.42.2"

forward-zone:
    name: "lan."
    forward-addr: 127.0.0.1@5553

forward-zone:
    name: "42.168.192.in-addr.arpa"
    forward-addr: 127.0.0.1@5553
