source_directories:
    - /home/mendess/vault
    - /home/mendess/tower/spire/home-assistant/backups
    - /vault/gallery

repositories:
    - path: /backups/self/repo
      label: local
      encryption: repokey-blake2
    - path: ssh://flopy//hdd/@backups/mendess/repo
      label: flopy
      storage_quota: 1024G
      encryption: repokey-blake2

patterns:
    - '! /home/mendess/vault/basement/rtp-memoria-dl'
    - '! /home/mendess/vault/alto-marr/torrents'
    - '! /home/mendess/vault/spire/homer'
    - '! /home/mendess/vault/spire/nextcloud/data'
    - '! /home/mendess/vault/spire/nextcloud/pw'
    # mariadb databases
    - '! /home/mendess/vault/spire/nextcloud/mariadb'
    # psql databases
    - '! /home/mendess/vault/basement/db'
    - '! /home/mendess/vault/gallery/immich/db'
    - '! /home/mendess/vault/spire/tandoor_db'

ssh_command: ssh -F /home/mendess/.ssh/config

user_runtime_directory: /tmp/borgmatic

compression: zstd,6
keep_daily: 8
keep_weekly: 8
keep_monthly: 6
keep_yearly: 1
retries: 3
retry_wait: 10
# borg_base_directory: /home/mendess/.local/share/borg
# log_file: /home/mendess/.local/share/borgmatic/logfile.txt
progress: true
statistics: true

commands:
  - before: configuration
    run:
      - bash /home/mendess/tower/portal/setup-mariadb-credentials.sh init
  - after: action
    when: [create]
    run:
      - /usr/local/bin/monitor-backups {repository_label}
  - after: error
    when: [create, prune]
    run:
      - /usr/local/bin/notify-hass backup-notification repository={repository_label} "message={error}"

postgresql_databases:
  - name: blind_eternities
    pg_dump_command: docker exec --user 1000 db pg_dump -U postgres
  - name: immich
    pg_dump_command: docker exec --user 1000 immich_postgres pg_dump -U postgres
  - name: tandoor
    pg_dump_command: docker exec --user 1000 tandoor_db pg_dump -U postgres

mariadb_databases:
  - name: nextcloud
    mariadb_dump_command: docker exec nextcloud-mariadb mariadb-dump
    options: --defaults-extra-file=/tmp/credentials.cnf --default-character-set=utf8mb4

encryption_passphrase: "{credential systemd borgmatic.pw}"
