source_directories:
    - /home/mendess/vault
    - /home/mendess/tower/spire/home-assistant/backups
    - /vault/gallery

repositories:
    - path: /backups/self/repo
      label: local
      encryption: repokey-blake2
    - path: ssh://flopy//hdd/@backups/mendess/repo
      label: flopy
      storage_quota: 1024G
      encryption: repokey-blake2

patterns:
    - '- /home/mendess/vault/basement/rtp-memoria-dl'
    - '- /home/mendess/vault/alto-marr/torrents'
    - '- /home/mendess/vault/spire/homer'
    - '! /home/mendess/vault/spire/nextcloud/data'
    - '! /home/mendess/vault/spire/nextcloud/mariadb'
    - '- /home/mendess/vault/spire/nextcloud/pw'

compression: zstd,6
keep_daily: 8
keep_weekly: 8
keep_monthly: 6
keep_yearly: 1
retries: 3
retry_wait: 10
# borg_base_directory: /home/mendess/.local/share/borg
# log_file: /home/mendess/.local/share/borgmatic/logfile.txt
progress: true
statistics: true

commands:
  - before: configuration
    run:
      - /home/mendess/tower/portal/setup-mariadb-credentials.sh
  - after: action
    when: [create]
    run:
      - /usr/local/bin/notify-hass latest-backup-update repository={repository_label}
  - after: error
    when: [create, prune]
    run:
      - /usr/local/bin/notify-hass backup-notification repository={repository_label} "message={error}"

postgresql_databases:
  - name: blind_eternities
    hostname: 127.0.0.1
    pg_dump_command: timeout 1h docker exec --user 1000 db pg_dump -U postgres

mariadb_databases:
  - name: nextcloud
    hostname: 127.0.0.1
    mariadb_dump_command: docker exec --user 1000 nextcloud-mariadb mariadb-dump --defaults-extra-file=/tmp/credentials.cnf --single-transaction --default-character-set=utf8mb4
